[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monitorai" 
version = "0.1.0"
description = "An observability SDK for Monitoring Machines Lab designed for machine learning workflow. Monitor and observe."
authors = [
    {name = "Masemene Matlakana Benny", email = "bennymasemene46@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "scipy>=1.10.0",
    "requests>=2.32.0",
    "pydantic>=1.10.16"
]

[project.urls]
Homepage = "https://github.com/MasemeneMatlakanaBenny/monitorai"
Issues = "https://github.com/MasemeneMatlakana/monitorai/issues"

[tool.setuptools]
package-dir = {"" = "src"}
packages = { find = { where = ["src"], include = ["monitorai", "monitorai.*"] } }
